# docker-compose up smart-brain-api

version: '3.7'

services:
  smart-brain-api:
    container_name: backend
    # image: node:8.11.1 - we build image from dockerfile
    build: ./
    command: yarn start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"